### ISSUE TITLE
Trimm error

### ISSUE THREAD

**Issue by chronoss09** [gibaBR/Switch-Backup-Manager#13]
It can't trimm Ys VIII Lacrimosa of DANA, it make done but do nothing on the dump...

**Comment by gibaBR** [comment]
can you try again? If still on error, put the log here.

**Comment by chronoss09** [comment]
Last version samething : 

2018-07-28 01:46:35.662 [INFO]    Starting trimming local files.
2018-07-28 01:46:35.682 [INFO]    Trimming file Ys VIII Lacrimosa of DANA.xci. Old size: 15971909632. New size: 15582880256
2018-07-28 01:46:35.904 [ERROR]   Error trimming file G:\XCI\Ys VIII Lacrimosa of DANA.xci
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Switch_Backup_Manager.Util.TrimXCIFile(FileData file)
2018-07-28 01:46:35.921 [INFO]    Finished trimming local files.

**Comment by gibaBR** [comment]
It happens only to this specific file? Maybe its a file permission issue or the file is corrupt?

**Comment by chronoss09** [comment]
Only with this file and the file isn't corrupt...
https://i.gyazo.com/a7cb4efc55e45c6df3d279817f07b526.png

**Comment by gibaBR** [comment]
I have this same file and could not reproduce the error. I really think the problem is your file.
