### ISSUE TITLE
Adding NSP bug

### ISSUE THREAD

**Issue by Gotcha007** [gibaBR/Switch-Backup-Manager#137]
Hi. I'm having some issues adding Dragon Quest Builder 2 and the DLCs.
2019-07-26 20:10:48.123 [DEBUG]   Found extra info for DLC on NSP local database
2019-07-26 20:10:48.664 [DEBUG]   searching for 010078D000F89002 in database.
2019-07-26 20:10:48.706 [INFO]    010078D000F89002 is already in database. Ignoring.
2019-07-26 20:10:48.754 [INFO]    Adding NSP file: DRAGON QUEST BUILDERS 2 [DLC Star Sigil block][010042000A987006][v0]
2019-07-26 20:10:48.995 [ERROR]      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2019-07-26 20:10:49.293 [WARNING] Could not retrieve image from the web for this title ( - ).
2019-07-26 20:10:49.378 [INFO]    Adding NSP file: DRAGON QUEST BUILDERS 2 [DLC Modernist Pack][010042000A987013][v0]
2019-07-26 20:10:49.624 [ERROR]      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2019-07-26 20:10:49.929 [WARNING] Could not retrieve image from the web for this title ( - ).
2019-07-26 20:10:50.009 [INFO]    Adding NSP file: DRAGON QUEST BUILDERS 2 [DLC Moon Sigil block][010042000A987007][v0]
2019-07-26 20:10:50.247 [ERROR]      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2019-07-26 20:10:50.537 [WARNING] Could not retrieve image from the web for this title ( - ).
2019-07-26 20:10:50.578 [INFO]    Finished the search for new files in Z:\Games\Roms\Nintendo Switch. 0 files added.

**Comment by garoxas** [comment]
Works for me
Try open your SBM directory and see if there's file named `meta` in there, and if you do please run this on command prompt
`hactool -k keys.txt -t pfs0 --section0dir=data meta`

**Comment by Gotcha007** [comment]
Hi, I do have a meta file in there.
When I run that command, I get this

C:\Switch.Backup.Manager.1.2.1>hactool -k keys.txt -t pfs0 --section0dir=data meta
[WARN] prod.keys does not exist.
Error: PFS0 is corrupt!

**Comment by garoxas** [comment]
my bad, it supposed to be
`hactool -k keys.txt --section0dir=data meta`

if it works, it'll create a `data` directory. please list the files here

**Comment by chris41g** [comment]
I have the same error and upon running that command

> hactool -k keys.txt --section0dir=data meta
> [WARN] prod.keys does not exist.
> 
> NCA:
> Magic:                              NCA3
> Fixed-Key Signature:                1AF9623F24776B9164496850E23AC7C585605C8633BF3616826E08F9D7E2FF1F
>                                     E5E9C9E5259BE22BE642A0EA3AF3A52893D9BCC2A0A1ED44DCA4F4A772ECA16B
>                                     8136B63330F68DBDB35A8C3B9A4ABB7B9F6454ADB36822D07596F7E057404AB0
>                                     5E0DEA876733E030A5C01859B9E61DEF1F61BC479205496DCB73FA076F451EF1
>                                     882C2CABA449B54AB9F47452FFE60A50BFE192691A7DCF3A42DE15DC53C8140D
>                                     3EA438D84DE9DC9605B00F4D8D441EA46CC87B8A7115EA2642C3D14318A40451
>                                     5B89A2612D1497FD0D6932537FD7223E1D61EFAACE6ED7578E6313858E9ED3CB
>                                     F7B4B50906BBEDD8AE9CE9A77CD81D190816DC7C86D692A13997740D84E8A036
> NPDM Signature:                     0000000000000000000000000000000000000000000000000000000000000000
>                                     0000000000000000000000000000000000000000000000000000000000000000
>                                     0000000000000000000000000000000000000000000000000000000000000000
>                                     0000000000000000000000000000000000000000000000000000000000000000
>                                     0000000000000000000000000000000000000000000000000000000000000000
>                                     0000000000000000000000000000000000000000000000000000000000000000
>                                     0000000000000000000000000000000000000000000000000000000000000000
>                                     0000000000000000000000000000000000000000000000000000000000000000
> Content Size:                       0x000000001000
> Title ID:                           010036200cf6a800
> SDK Version:                        7.3.0.0
> Distribution type:                  Download
> Content Type:                       Meta
> Master Key Revision:                7 (Unknown)
> Encryption Type:                    Standard crypto
> Key Area Encryption Key:            0
> Key Area (Encrypted):
>     Key 0 (Encrypted):              B11FA49BFAAF73D6E01487CF6366F43D
>     Key 1 (Encrypted):              B11FA49BFAAF73D6E01487CF6366F43D
>     Key 2 (Encrypted):              2C5C79D4CF2C434E13043EB746B24818
>     Key 3 (Encrypted):              B11FA49BFAAF73D6E01487CF6366F43D
> Key Area (Decrypted):
>     Key 0 (Decrypted):              156B99317D3E32818E782850F6654587
>     Key 1 (Decrypted):              156B99317D3E32818E782850F6654587
>     Key 2 (Decrypted):              295A606EB66C07A8226D8D6D61F341C5
>     Key 3 (Decrypted):              156B99317D3E32818E782850F6654587
> Sections:
>     Section 0:
>         Offset:                     0x000000000c00
>         Size:                       0x000000000400
>         Partition Type:             PFS0
>         Section CTR:                000000000000000000000000000000C0
>         Superblock Hash:            4887B335CCA92D9BC6082CA860826DA7932F38E4DD948ED0CAA0D0C310EF52D8
>         Hash Table:
>             Offset:                 000000000000
>             Size:                   000000000020
>             Block Size:             0x1000
>         PFS0 Offset:                000000000020
>         PFS0 Size:                  000000000214
> 
> Error: section 0 is corrupted!
> 
> Done!
It does not create a data folder

**Comment by garoxas** [comment]
check your keys.txt if it has all necessary master key entries
for best compatibility make sure that it has all to `master_key_08`
