### ISSUE TITLE
Some NSP files are stated as broken and have missing information

### ISSUE THREAD

**Issue by deadair3210** [gibaBR/Switch-Backup-Manager#165]
I have a couple nsp files every once in a while that will be missing information, the log states that they are broken and the names are not automatically fixed, instead retreating back to the file name. If I run the files through a program to verify them, they come back perfect, so am I missing something?

**Comment by deadair3210** [comment]
here is a log from one of the nsps run through the program to verify them
https://pastebin.com/c36gfSpR

**Comment by deadair3210** [comment]
Interestingly,rebuilding the nsp files seems to mostly fix them, maybe the program is having a issue with the internal order of the files or something?

**Comment by garoxas** [comment]
it's this game right?

<img width="660" alt="sbm" src="https://user-images.githubusercontent.com/11901820/70861012-1602f900-1f5b-11ea-97d2-f6416e627e56.PNG">

> 
> 
> the log states that they are broken and the names are not automatically fixed

if you meant this log message then you shouldn't need to worry, the app just try to find the game name from titlekeys.txt file which I believe most users don't have one anyway

```
[INFO]    Could not find game name! Don't worry, will try again later
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
```

> 
> 
> maybe the program is having a issue with the internal order of the files or something?

not sure about having issue with the files order, but it does read files based on its order in the file entry table

**Comment by deadair3210** [comment]
A lot of my files seem to have the issue, the only solution I have found is to rebuild the nsp with something like NSC_Builder. What's weird is the issue only started happening, the backup manager was working fine a week ago

**Comment by deadair3210** [comment]
Lots of complaints of Section 00 being missing as well

**Comment by garoxas** [comment]
you can try to replace hactool in your sbm app directory

**Comment by deadair3210** [comment]
Updating hactool seems to have cleared up some of it, you might want to look into updating the build that the program grabs
