### ISSUE TITLE
nstoolmod.exe has stopped working upon attempting to scan eShop files

### ISSUE THREAD

**Issue by cryptolute** [gibaBR/Switch-Backup-Manager#24]
As soon as I select the folder nstoolmod.exe gets called and then immediately throws up a error that it has stopped working.

I have disabled my AV. Attached is the error log...

Looking at the error, it appears that it cannot create a dir? Unsure. The drive definitely has 600+GB of free space. I've also tried running it as admin, log below the first one.

I also tried manually selecting a diff nsp instead of by folder to see what would happen and the same issue occured.

I can run nstoolmod.exe from command line, doesn't appear to be any issues? If there's a particular argument you want me to try let me know I"ll give it a whirl via cmd line.

Thanks!

2018-08-02 17:13:08.770 sbm.log is created.
2018-08-02 17:13:13.545 [INFO]    Start removing missing files from local database
2018-08-02 17:13:13.571 [INFO]    Finished removing missing files from local database. 0 files removed.
2018-08-02 17:13:13.603 [INFO]    Start removing missing files from e-shop database
2018-08-02 17:13:13.619 [INFO]    Finished removing missing files from e-shop database. 0 files removed.
2018-08-02 17:13:26.077 [INFO]    Adding 94 files on local Eshop database
2018-08-02 17:13:26.086 [INFO]    Adding NSP file: 4.4.0Fortnite [v0]010025400AECE000
2018-08-02 17:13:26.087 [INFO]    Extracting NSP file.
2018-08-02 17:13:55.647 [ERROR]   Directory tmp was not created ?!
2018-08-02 17:13:55.655 [ERROR]      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-08-02 17:13:55.667 [ERROR]      at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-08-02 17:13:55.671 [ERROR]      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
   at Switch_Backup_Manager.Util.AddFilesFromFolder(String path, String fileType)
2018-08-02 17:14:03.433 [INFO]    Adding 94 files on local Eshop database
2018-08-02 17:14:03.438 [INFO]    Adding NSP file: 4.4.0Fortnite [v0]010025400AECE000
2018-08-02 17:14:03.440 [INFO]    Extracting NSP file.
2018-08-02 17:14:10.528 [ERROR]   Directory tmp was not created ?!
2018-08-02 17:14:10.531 [ERROR]      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-08-02 17:14:10.545 [ERROR]      at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-08-02 17:14:10.546 [ERROR]      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
   at Switch_Backup_Manager.Util.AddFilesFromFolder(String path, String fileType)
2018-08-02 17:14:53.947 [INFO]    Adding 94 files on local Eshop database
2018-08-02 17:14:53.952 [INFO]    Adding NSP file: 4.4.0Fortnite [v0]010025400AECE000
2018-08-02 17:14:53.954 [INFO]    Extracting NSP file.
2018-08-02 17:14:56.965 [ERROR]   Directory tmp was not created ?!
2018-08-02 17:14:56.968 [ERROR]      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-08-02 17:14:56.970 [ERROR]      at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-08-02 17:14:56.973 [ERROR]      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
   at Switch_Backup_Manager.Util.AddFilesFromFolder(String path, String fileType)

And here is running as administrator -

2018-08-02 17:19:14.998 [INFO]    Start removing missing files from local database
2018-08-02 17:19:15.027 [INFO]    Finished removing missing files from local database. 0 files removed.
2018-08-02 17:19:15.058 [INFO]    Start removing missing files from e-shop database
2018-08-02 17:19:15.067 [INFO]    Finished removing missing files from e-shop database. 0 files removed.
2018-08-02 17:19:23.243 [INFO]    Adding 94 files on local Eshop database
2018-08-02 17:19:23.252 [INFO]    Adding NSP file: 4.4.0Fortnite [v0]010025400AECE000
2018-08-02 17:19:23.254 [INFO]    Extracting NSP file.
2018-08-02 17:19:32.690 [ERROR]   Directory tmp was not created ?!
2018-08-02 17:19:32.694 [ERROR]      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-08-02 17:19:32.699 [ERROR]      at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-08-02 17:19:32.701 [ERROR]      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
   at Switch_Backup_Manager.Util.AddFilesFromFolder(String path, String fileType)

**Comment by billysun76** [comment]
I got the same problem.

**Comment by cryptolute** [comment]
billysun76 - Win 7 or win 10?

Win 10 is working for me, win 7 not.

**Comment by gibaBR** [comment]
Hum... I'll make a VM with win7 to try

Em sex, 3 de ago de 2018 15:59, crypt <notifications@github.com> escreveu:

**Comment by ceedveed** [comment]
nstoolmod stopped for me too. I'm on Windows 7

**Comment by strik3** [comment]
getting the same error on windowsserver 2008 r2

**Comment by chronoss09** [comment]
Windows 7



![121d0b514f0ea78373efc5b7cd24c6b4](https://user-images.githubusercontent.com/17669980/43677485-8befbdd6-97fa-11e8-953b-047b39c9d143.png)

**Comment by vaccarieli** [comment]
For me it does not stop, but when i try to load up the eshop game it only load 125 files but i have 800 and some, don't what the problem is.

**Comment by gibaBR** [comment]
Program does not use nstoolmod.exe anymore
