### ISSUE TITLE
System.Version.VersionResult.SetFailure

### ISSUE THREAD

**Issue by alaindesjardins** [gibaBR/Switch-Backup-Manager#42]
I can't seem to scrape some games... not sure why but this is my first time using the tool.

`2018-08-21 11:58:17.081 sbm.log is created.
2018-08-21 11:58:23.595 [INFO]    Searchng for new files on E:\Switch
2018-08-21 11:58:46.658 [INFO]    Adding 10 files on local database
2018-08-21 11:58:48.323 [INFO]    Scraping file E:\Switch\bbb-h-aejqb-cut.xci, TitleID: 0100B1F00660E000
2018-08-21 11:58:49.197 [INFO]    Scraping file E:\Switch\bbb-h-acatc-cut.xci, TitleID: 0100562008698000
2018-08-21 11:58:50.630 [INFO]    Scraping file E:\Switch\hr-alera-cut.xci, TitleID: 0100BDE00862A000
2018-08-21 11:58:51.951 [ERROR]      at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at Switch_Backup_Manager.Util.GetFileData(String filepath)
   at Switch_Backup_Manager.Util.AddFilesFromFolder(String path, String fileType)
2018-08-21 11:58:51.989 [DEBUG]   searching for 0100B1F00660E000 on database.
2018-08-21 11:58:52.009 [INFO]    0100B1F00660E000 was already on database. Ignoring.
2018-08-21 11:58:52.028 [DEBUG]   searching for 0100562008698000 on database.
2018-08-21 11:58:52.057 [INFO]    0100562008698000 was already on database. Ignoring.
2018-08-21 11:58:52.074 [DEBUG]   searching for 0100BDE00862A000 on database.
2018-08-21 11:58:52.092 [INFO]    0100BDE00862A000 was already on database. Ignoring.
`

**Comment by garoxas** [comment]
can you narrow it down to which games failing when scraping the info?
it looks like it's failing on Mario Tennis Aces (hr-alera-cut.xci), but I have that and tested it (both trimmed and untrimmed) without issue

@gibaBR looks like regression from my latest commit judging by the log file (failing at System.Version.Parse)
you can wrap it in try-catch for quick fix but I was curious what was the actual problem (empty string on control.nacp? not likely)
