### ISSUE TITLE
Fail to process XCI, Rocket League Ultimate Edition NSW-VENOM release

### ISSUE THREAD

**Issue by Stone-D** [gibaBR/Switch-Backup-Manager#57]
```
2018-09-06 07:47:10.335 [INFO]    Adding 1 files on local database.
2018-09-06 07:47:10.466 [ERROR]      at Switch_Backup_Manager.Util.GetFileData(String filepath)
   at Switch_Backup_Manager.Util.AddFiles(String[] files, String fileType)

```

**Comment by garoxas** [comment]
duplicate #54
