### ISSUE TITLE
Adding NSP file bug

### ISSUE THREAD

**Issue by tom5151** [gibaBR/Switch-Backup-Manager#73]
I have some nsp files that I can not add.
Here is the log file:

> 2018-10-07 21:00:49.189 [INFO]    Adding 8 files on local Eshop database.
2018-10-07 21:00:49.199 [INFO]    Adding NSP file: sxs-htad
2018-10-07 21:00:49.203 [INFO]    Making some voodoo magic with 
2018-10-07 21:00:49.244 [ERROR]    seems to be broken! Some info will be missing.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-10-07 21:00:49.274 [INFO]    Adding NSP file: sxs-htau
2018-10-07 21:00:49.277 [INFO]    Making some voodoo magic with 
2018-10-07 21:00:49.319 [ERROR]    seems to be broken! Some info will be missing.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-10-07 21:00:49.346 [ERROR]   TitleID  is already on database.
2018-10-07 21:00:49.349 [INFO]    Adding NSP file: sxs-rdd4
2018-10-07 21:00:49.353 [INFO]    Making some voodoo magic with 
2018-10-07 21:00:49.392 [ERROR]    seems to be broken! Some info will be missing.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-10-07 21:00:49.419 [ERROR]   TitleID  is already on database.
2018-10-07 21:00:49.422 [INFO]    Adding NSP file: sxs-rdd1
2018-10-07 21:00:49.424 [INFO]    Making some voodoo magic with 
2018-10-07 21:00:49.465 [ERROR]    seems to be broken! Some info will be missing.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-10-07 21:00:49.482 [ERROR]   TitleID  is already on database.
2018-10-07 21:00:49.486 [INFO]    Adding NSP file: sxs-rdd2
2018-10-07 21:00:49.488 [INFO]    Making some voodoo magic with 
2018-10-07 21:00:49.527 [ERROR]    seems to be broken! Some info will be missing.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-10-07 21:00:49.553 [ERROR]   TitleID  is already on database.
2018-10-07 21:00:49.556 [INFO]    Adding NSP file: sxs-o2d2
2018-10-07 21:00:49.558 [INFO]    Making some voodoo magic with 
2018-10-07 21:00:49.597 [ERROR]    seems to be broken! Some info will be missing.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-10-07 21:00:49.614 [ERROR]   TitleID  is already on database.
2018-10-07 21:00:49.618 [INFO]    Adding NSP file: sxs-tnte
2018-10-07 21:00:49.622 [INFO]    Making some voodoo magic with 
2018-10-07 21:00:49.662 [ERROR]    seems to be broken! Some info will be missing.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-10-07 21:00:49.681 [ERROR]   TitleID  is already on database.
2018-10-07 21:00:49.684 [INFO]    Adding NSP file: v-nba19u
2018-10-07 21:00:49.691 [INFO]    Making some voodoo magic with 
2018-10-07 21:00:49.734 [ERROR]    seems to be broken! Some info will be missing.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-10-07 21:00:49.760 [ERROR]   TitleID  is already on database.
2018-10-07 21:00:49.762 [INFO]    Finished adding files. Total time was 00:00.56.
2018-10-07 21:00:49.765 [DEBUG]   searching for  on database.
2018-10-07 21:00:49.767 [INFO]     was already on database. Ignoring.

**Comment by garoxas** [comment]
can you provide more details? I'm having difficulty finding what games you were testing with

all I can find based on the filename of your files was **sxs-htau** which is DLC for SNK Heroines. it's a 120 kB NSP with lacking several necessary files required by SBM
are you sure that this NSP can be installed without issue?

**Comment by tom5151** [comment]
Here is the list:
- NBA_2K19_Update_v1.01_NSW-VENOM
- Overcooked_2_Surf_n_Turf_DLC_NSW-SUXXORS
- Revenant_Dogma_Damage_Orichalcum_DLC_NSW-SUXXORS
- Revenant_Dogma_Encounter_Orichalcum_DLC_NSW-SUXXORS
- Revenant_Dogma_Experience_Orichalcum_DLC_NSW-SUXXORS
- SNK_Heroines_Tag_Team_Frenzy_Thief_Arthur_USA_DLC_NSW-SUXXORS
- Taiko_no_Tatsujin_Nintendo_Switch_Version_Update_v1.0.3_READNFO_NSW-SUXXORS

All the DLC are 120kB and have been released on the scene, so I would say they should be installable.
The 2 updates are bigger  (26Go and 340Mo)

**Comment by garoxas** [comment]
can you try this
https://mega.nz/#!lRt0WCoQ!FHUGQXn2fypSab8P_fLNzRAZArXYv8iIsIN1pvewYlc

I only tested using SNK Heroines DLC and since I don't have the base game so the other details (game name, developer, language) are missing. see if it works for you if you paired it with base game/updates

https://www.virustotal.com/#/file/5b6f261a665457b084d88e4f67531bea4e263888bd35761072ea35c9d6775daf/detection for the paranoids 😈

**Comment by tom5151** [comment]
I've just tried.
It's working fine.
Thanks a lot for your support !
