### ISSUE TITLE
Error adding NSP files

### ISSUE THREAD

**Issue by Echelon01** [gibaBR/Switch-Backup-Manager#78]
Hello!

I can't add some games, DLC or Updates to my eShop List.
Probably the scene group removed information from the nsp.

I let you the log to check it

Is there something I can do to solve that?

Thanks!!

2018-10-17 22:25:32.256 [INFO]    Adding NSP file: [0100A250097F1008][v0]
2018-10-17 22:25:32.274 [ERROR]   TitleID  is already on database.
2018-10-17 22:25:32.298 [INFO]    Adding NSP file: [01005C600AC69007][v0]
2018-10-17 22:25:32.320 [DEBUG]   Analyzing xml file.
2018-10-17 22:25:32.336 [ERROR]      at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-10-17 22:25:32.835 [WARNING] Could not retrieve image from the web for this title ( - ).
2018-10-17 22:25:33.210 [ERROR]   TitleID  is already on database.
2018-10-17 22:25:33.491 [INFO]    Adding NSP file: Gear Club Unlimited DLC Unlocker  
2018-10-17 22:25:34.256 [INFO]    Making some voodoo magic with 
2018-10-17 22:25:34.861 [ERROR]    seems to be broken! Some info will be missing.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-10-17 22:25:35.534 [WARNING] Could not retrieve image from the web for this title ( - ).
2018-10-17 22:25:35.558 [ERROR]   TitleID  is already on database.
2018-10-17 22:25:35.595 [INFO]    Adding NSP file: Overcooked 2 Surf n Turf DLC
2018-10-17 22:25:35.632 [INFO]    Making some voodoo magic with 
2018-10-17 22:25:35.769 [ERROR]    seems to be broken! Some info will be missing.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-10-17 22:25:36.311 [WARNING] Could not retrieve image from the web for this title ( - ).
2018-10-17 22:25:36.332 [ERROR]   TitleID  is already on database.
2018-10-17 22:25:36.372 [INFO]    Adding NSP file: Pinball FX3 Williams Pinball Volume 1 DLC  
2018-10-17 22:25:36.414 [DEBUG]   Analyzing xml file.
2018-10-17 22:25:36.568 [DEBUG]   Found extra info for DLC on Scene database
2018-10-17 22:25:38.704 [INFO]    Adding NSP file: Revenant Dogma Damage Orichalcum DLC
2018-10-17 22:25:38.728 [INFO]    Making some voodoo magic with 
2018-10-17 22:25:38.867 [ERROR]    seems to be broken! Some info will be missing.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-10-17 22:25:39.398 [WARNING] Could not retrieve image from the web for this title ( - ).
2018-10-17 22:25:39.418 [ERROR]   TitleID  is already on database.
2018-10-17 22:25:39.454 [INFO]    Adding NSP file: Revenant Dogma Encounter Orichalcum DLC
2018-10-17 22:25:39.494 [INFO]    Making some voodoo magic with 
2018-10-17 22:25:39.645 [ERROR]    seems to be broken! Some info will be missing.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-10-17 22:25:40.185 [WARNING] Could not retrieve image from the web for this title ( - ).
2018-10-17 22:25:40.213 [ERROR]   TitleID  is already on database.
2018-10-17 22:25:40.253 [INFO]    Adding NSP file: Revenant Dogma Experience Orichalcum DLC
2018-10-17 22:25:40.291 [INFO]    Making some voodoo magic with 
2018-10-17 22:25:40.433 [ERROR]    seems to be broken! Some info will be missing.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-10-17 22:25:41.091 [WARNING] Could not retrieve image from the web for this title ( - ).
2018-10-17 22:25:41.113 [ERROR]   TitleID  is already on database.
2018-10-17 22:25:41.153 [INFO]    Adding NSP file: Revenant Dogma Full Recovery Orichalcum DLC
2018-10-17 22:25:41.196 [INFO]    Making some voodoo magic with 
2018-10-17 22:25:41.332 [ERROR]    seems to be broken! Some info will be missing.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-10-17 22:25:41.854 [WARNING] Could not retrieve image from the web for this title ( - ).
2018-10-17 22:25:41.877 [ERROR]   TitleID  is already on database.
2018-10-17 22:25:41.917 [INFO]    Adding NSP file: SNK Heroines Tag Team Frenzy v1.20 DLC Unlocker  
2018-10-17 22:25:41.958 [INFO]    Making some voodoo magic with 
2018-10-17 22:25:42.094 [ERROR]    seems to be broken! Some info will be missing.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-10-17 22:25:42.640 [WARNING] Could not retrieve image from the web for this title ( - ).
2018-10-17 22:25:42.661 [ERROR]   TitleID  is already on database.
2018-10-17 22:25:42.698 [INFO]    Adding NSP file: Starlink Battle For Atlas DLC Unlocker NSW-VENOM
2018-10-17 22:25:42.739 [INFO]    Making some voodoo magic with 
2018-10-17 22:25:42.877 [ERROR]    seems to be broken! Some info will be missing.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-10-17 22:25:43.412 [WARNING] Could not retrieve image from the web for this title ( - ).
2018-10-17 22:25:43.438 [ERROR]   TitleID  is already on database.
2018-10-17 22:25:43.480 [INFO]    Adding NSP file: Starlink UnlockDLC
2018-10-17 22:25:43.523 [INFO]    Making some voodoo magic with 
2018-10-17 22:25:43.667 [ERROR]    seems to be broken! Some info will be missing.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-10-17 22:25:44.218 [WARNING] Could not retrieve image from the web for this title ( - ).
2018-10-17 22:25:44.251 [ERROR]   TitleID  is already on database.
2018-10-17 22:25:44.290 [INFO]    Adding NSP file: Taiko no Tatsujin Nintendo Switch Version DLC Unlocker  
2018-10-17 22:25:44.334 [INFO]    Making some voodoo magic with 
2018-10-17 22:25:44.475 [ERROR]    seems to be broken! Some info will be missing.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-10-17 22:25:45.020 [WARNING] Could not retrieve image from the web for this title ( - ).
2018-10-17 22:25:45.043 [ERROR]   TitleID  is already on database.
2018-10-17 22:25:45.086 [INFO]    Adding NSP file: Taiko no Tatsujin Nintendo Switch Version v1 0 4 DLC Unlocker  
2018-10-17 22:25:45.124 [INFO]    Making some voodoo magic with 
2018-10-17 22:25:45.289 [ERROR]    seems to be broken! Some info will be missing.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-10-17 22:25:45.871 [WARNING] Could not retrieve image from the web for this title ( - ).
2018-10-17 22:25:45.891 [ERROR]   TitleID  is already on database.
2018-10-17 22:25:45.930 [INFO]    Adding NSP file: The Walking Dead Final Season Episode 2 DLC READNFO  
2018-10-17 22:25:45.971 [INFO]    Making some voodoo magic with 
2018-10-17 22:25:46.112 [ERROR]    seems to be broken! Some info will be missing.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Switch_Backup_Manager.Util.GetFileDataNSP(String file)
2018-10-17 22:25:46.688 [WARNING] Could not retrieve image from the web for this title ( - ).
2018-10-17 22:25:46.711 [ERROR]   TitleID  is already on database.
2018-10-17 22:25:46.757 [INFO]    Finished adding files. Total time was 00:14.53.
2018-10-17 22:25:46.795 [DEBUG]   searching for  on database.
2018-10-17 22:25:46.836 [INFO]     was already on database. Ignoring.
2018-10-17 22:25:46.877 [DEBUG]   searching for 0100DB700382900E on database.
2018-10-17 22:25:46.916 [DEBUG]   0100DB700382900E not found on database. Adding...
2018-10-17 22:25:46.953 [DEBUG]   Adding element...
2018-10-17 22:25:46.995 [DEBUG]   Saving xml SBM_NSP_Local.xml
2018-10-17 22:25:47.039 [DEBUG]   xml saved...

**Comment by garoxas** [comment]
dupe #73 
should be fixed in next release

**Comment by Echelon01** [comment]
Hello there garoxas!
Thanks and sorry for the dupe :(

Yes indeed it is, Valkyria Chronicles 4 Japaneses voices.

**Comment by garoxas** [comment]
works for me
although the screenshot below was taken from the latest commit, but I've also tested with 1.1.8 and it works

<img width="1159" alt="vc4_1" src="https://user-images.githubusercontent.com/11901820/47167722-5a7c1000-d329-11e8-9042-13199d71caac.PNG">
<img width="511" alt="vc4_2" src="https://user-images.githubusercontent.com/11901820/47167724-5b14a680-d329-11e8-9027-887b9328ad83.PNG">

if you want, you can attach the xml here to be analyzed
and just in case here's the hactool command to extract the NSP
```hactool -t pfs0 --pfs0dir=<some directory> "[01005C600AC69007][v0].dlc"```

and please attach all the xmls in that directory here
thanks
